name: Metrics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 21 * * *'

  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          plugin_followup: yes
          plugin_followup_sections: user
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_reactions: yes
          plugin_reactions_details: count, percentage
          plugin_achievements: yes
          plugin_activity: yes
